[package]
name = "application"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common = { path = "../common" }
domain = { path = "../domain" }
mockall = "0.11.0"
ports = { path = "../ports" }
thiserror = "1.0.30"
tokio = { version = "1.18.4", features = ["macros", "rt-multi-thread"] }
