[package]
name = "domain"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common = { path = "../common" }
dyn-clone = "1.0.4"
thiserror = "1.0.30"

[dev-dependencies]
rstest = "0.12.0"
