[package]
name = "common"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.51"
async-trait = "0.1.52"
futures = "0.3.19"
uuid = { version = "0.8.2", features = ["serde", "v4"] }
